// /js/modules/payload.js

import { UIModule } from './ui.js';
import { QRModule } from './qr.js';
import { ClipboardModule } from './clipboard.js';

/**
 * PayloadModule - Handles payload string generation, parsing, and management
 *
 * Features:
 * - Generate payload strings from encrypted data
 * - Parse and decode CipherBrick payload strings
 * - Toggle payload input UI visibility
 * - Apply decoded payloads to the application
 */
export class PayloadModule {
    constructor(app) {
        this.app = app;
    }

    get i18n() { return this.app?.i18nStrings || {}; }

    /**
     * Generate a payload string from the current encrypted output
     * Copies the payload to clipboard and hides the QR modal
     */
    generatePayloadString() {
        const encryptBtn = document.getElementById("encryptBtn");
        if (!encryptBtn.classList.contains("mode-button-active")) {
            UIModule.showMessage(this.i18n.payload_encrypt_only || "Payload generation is only available in Encrypt mode.", "warning");
            return;
        }

        const encryptedMessage = document.getElementById("outputText").value;
        if (!encryptedMessage) {
            UIModule.showMessage(this.i18n.payload_no_encrypted || "No encrypted message found. Please run encryption first.", "warning");
            return;
        }

        const stealth = sessionStorage.getItem("stealthMode") === "true";
        const payload = QRModule.createQRPayload("encrypt", encryptedMessage, stealth);

        ClipboardModule.copyToClipboard(payload, UIModule, () => this.app.updateStatusBar(), this.i18n);

        const qrModalEl = document.getElementById("qrModal");
        const qrModal = bootstrap.Modal.getInstance(qrModalEl) || new bootstrap.Modal(qrModalEl);
        qrModal.hide();
    }

    /**
     * Toggle the visibility of the payload input area
     * Hides audio receiver when showing payload input
     */
    togglePayloadInput() {
        const payloadArea = document.getElementById('payloadInputArea');
        const audioArea = document.getElementById('audioReceiver');

        const isCurrentlyVisible = payloadArea?.style.display === 'block';

        if (audioArea) audioArea.style.display = 'none';

        if (payloadArea) {
            payloadArea.style.display = isCurrentlyVisible ? 'none' : 'block';
            if (!isCurrentlyVisible) {
                document.getElementById('pastedPayload')?.focus();
            }
        }
    }

    /**
     * Use a pasted payload string from the context area
     * Parses the payload and applies it to the input field
     */
    usePayloadString() {
        const payload = document.getElementById('pastedPayload').value.trim();
        if (!payload) return;

        // Validate CipherBrick payload format
        const parsed = QRModule.parseCipherBrickQR(payload);

        if (!parsed) {
            UIModule.showMessage(this.i18n.payload_invalid || "Invalid payload. Paste the text string generated by CipherBrick's Payload button.", "warning");
            return;
        }

        // Handle stealth mode — sync mode dropdown and storage to match payload type
        if (parsed.stealth) {
            sessionStorage.setItem("stealthMode", "true");
            localStorage.setItem("cb.simplifiedMode", "true");
            localStorage.setItem("cb.hardwareKeyMode", "false");
            const modeSelect = document.getElementById("modeSelect");
            if (modeSelect) modeSelect.value = "simple";
        } else {
            sessionStorage.setItem("stealthMode", "false");
            localStorage.setItem("cb.simplifiedMode", "false");
            const modeSelect = document.getElementById("modeSelect");
            if (modeSelect && modeSelect.value === "simple") modeSelect.value = "standard";
        }
        UIModule.updateStealthUI();

        // Force decrypt mode if original was encrypt
        const newMode = (parsed.mode === "encrypt") ? "decrypt" : parsed.mode;
        if (newMode !== this.app.currentMode) {
            this.app.setMode(newMode);
        }

        // Fill the input field, then clear and close
        document.getElementById("inputText").value = parsed.payload;
        UIModule.showMessage(this.i18n.payload_loaded || "Payload loaded successfully.", "success");

        document.getElementById('pastedPayload').value = '';
        document.getElementById('payloadInputArea').style.display = 'none';
    }
}
